--- 
# put your config here, since terminitor doesn't (yet) support passing parameters when starting a project
dir: ~/workspace
port: 3456
# will be dev3 eventually
server: dev3
commands:
  server: 
    rails2: ruby script/server
    rails3: rails server
    sinatra: ??
  console: 
    rails2: ruby script/console
    rails3: rails console
    sinatra: ??
# dev.term assumes rails2 unless otherwise noted here
# use the app's directory name as the key
apps: 
  circadjs: rails3
  genesys-readonly: rails3

