" Default gui color scheme
set background=light
" colorscheme solarized
colorscheme github
set gfn=Monaco:h14 " set to a bigger, nicer font than the default
" Command-Shift-F for Ack
map <D-F> :Ack<space>
" Ctrl-Shift-F for Ack on current word
map <C-F> :Ack<space><cword><space>

" Command-/ to toggle comments
map <D-/> <plug>NERDCommenterToggle<CR>
imap <D-/> <Esc><plug>NERDCommenterToggle<CR>i

" Command-][ to increase/decrease indentation
vmap <D-]> >gv
vmap <D-[> <gv

" Adjust viewports to the same size
map <Leader>= <C-w>=
imap <Leader>= <Esc> <C-w>=

" Any MacVim-specific settings
if has("gui_macvim")
  " Command-T for CommandT, and Command-Shift-T for New Tab
  macmenu &File.New\ Tab key=<D-T>
  map <D-t> :CommandT<CR>
  imap <D-t> <Esc>:CommandT<CR>

  set fuoptions=maxhorz,maxvert " Fullscreen takes up entire screen
  set guioptions-=T " Start without the toolbar

  " Command+/ to comment or uncomment the line, using commentary plugin
  map <D-/> <Leader>\\
endif


