if [ -f /opt/homebrew/bin/brew ]
then
  eval "$(/opt/homebrew/bin/brew shellenv)"
elif [ -f /usr/local/bin/brew ]
then
  eval "$(/usr/local/bin/brew shellenv)"
fi

# Different apps look for different variables to options for Make
export MAKE_OPTS="-j$(nproc)"
export MAKEOPTS="-j$(nproc)"
