# enable zsh autocompletion
autoload -U promptinit
promptinit

autoload -U compinit
compinit
zmodload -i zsh/complist

autoload colors; colors

if [[ -e ~/.zsh ]]; then
  for a in `ls ~/.zsh/*.zsh`; do
    # echo sourcing $a
    source $a
  done
fi

[ -f ~/.zshrc.local ] && source ~/.zshrc.local
