# enable zsh autocompletion
autoload -U promptinit
promptinit

autoload -U compinit
compinit
zmodload -i zsh/complist

autoload colors; colors

# add this repo's bin to PATH
export PATH=~/bin:$PATH
# add dropbox to PATH
export PATH=/Users/pbyrne/Dropbox/bin:$PATH
# and local mysql install
export PATH=/usr/local/mysql/bin:$PATH
# and homebrew
export PATH=/usr/local/bin:/usr/local/sbin:$PATH
# and the currently install NPM-installed executables
export PATH=./node_modules/.bin:$PATH
# Display time to complete commands longer than $REPORTTIME
export REPORTTIME=5

# i have a color screen, you know
export TERM='xterm-color'


if [[ -e ~/.zsh ]]; then
  for a in `ls ~/.zsh/*.zsh`; do
    # echo sourcing $a
    source $a
  done
fi

[ -f ~/.zshrc.local ] && source ~/.zshrc.local

### Added by the Heroku Toolbelt
export PATH="/usr/local/heroku/bin:$PATH"

