# enable zsh autocompletion
autoload -U promptinit
promptinit

autoload -U compinit
compinit
zmodload -i zsh/complist

autoload colors; colors

# add this repo's bin to PATH
export PATH=~/bin:$PATH
# add dropbox to PATH
export PATH=/Users/pbyrne/Dropbox/bin:$PATH
# and homebrew
export PATH=/usr/local/bin:/usr/local/sbin:$PATH
# Display time to complete commands longer than $REPORTTIME
export REPORTTIME=5

# i have a color screen, you know
export TERM='xterm-color'


if [[ -e ~/.zsh ]]; then
  for a in `ls ~/.zsh/*.zsh`; do
    # echo sourcing $a
    source $a
  done
fi

eval "$(rbenv init -)"
eval "$(boot2docker shellinit 2>/dev/null)"

[ -f ~/.zshrc.local ] && source ~/.zshrc.local
